version: "3"
services:
  node:
    build:
      context: ./node
    container_name: node
    hostname: node
    ports:
      - "3000:3000"
    
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    hostname: nginx
    ports: 
      - "80:80"
    depends_on:
      - node

  mariadb:
    build:
        context: ./mariadb
    container_name: mariadb
    hostname: mariadb
    ports: 
      - "3306:3306"