FROM node:latest
RUN git clone https://github.com/LeonelAlegreDev/node-api-structure /var/www/node-app
WORKDIR /var/www/node-app
COPY .env /var/www/node-app/.env
RUN npm install pm2
RUN npm install
EXPOSE 3000